config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  match '/users',   to: 'users#index',   via: 'get'
  resources :artifacts
  resources :projects
  devise_for :users
  root 'home#index'

  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artifact.rb
class Artifact < ApplicationRecord
  # attr_accessor :photo
  has_one_attached :photo
  belongs_to :project

  validates_presence_of :name, :photo
  validates_uniqueness_of :name
  # validate :photo_file_size
  validate :acceptable_image



  private

  def acceptable_image
    return unless photo.attached?

    unless photo.blob.byte_size <= 2.megabyte
      errors.add(:upload, "must be less than 2mb")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(photo.content_type)
      errors.add(:upload, "must be a JPEG or PNG")
    end
  end

end

app/models/plan.rb
class Plan
  PLANS = [:free, :premium]
  def self.options
    PLANS.map {|plan| [plan.capitalize, plan]}
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
  has_many :artifacts, dependent: :destroy
  belongs_to :user
  validate :free_plan_can_only_have_one_project

  def free_plan_can_only_have_one_project
    if self.new_record? && (user.projects.count > 0) && (user.paid? == false)
      errors.add(:base, "Free plans cannot have more than one project")
    end

end
end

app/models/tenant.rb
class Tenant < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  has_one :payment
  has_many :projects, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  pay_customer stripe_attributes: :stripe_attributes

  def stripe_attributes(pay_customer)
    {
      address: {
        city: pay_customer.owner.city,
        country: pay_customer.owner.country
      },
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id # or pay_customer.owner_id
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /artifacts or /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1 or /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    @artifact.project_id = params[:project_id]
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts or /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to artifact_url(@artifact), notice: "Artifact was successfully created." }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1 or /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to artifact_url(@artifact), notice: "Artifact was successfully updated." }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1 or /artifacts/1.json
  def destroy
    @artifact.destroy!

    respond_to do |format|
      format.html { redirect_to project_path(@artifact.project_id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artifact_params
      params.require(:artifact).permit(:name, :key, :project_id, :photo)
    end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  def show
    current_user.set_payment_processor :stripe
    current_user.payment_processor.customer

    @checkout_session = current_user
                        .payment_processor
                        .checkout(
                          mode: 'subscription',
                          line_items: 'price_1PWtdKI4Zyhf3cOmWJ4OlIbP',
                          success_url: checkout_success_url
                            )
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @line_items = Stripe::Checkout::Session.list_line_items(params[:session_id])
    current_user.paid = true
    current_user.save!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_completion_date, :tenant_id, :user_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/artifacts/_artifact.html.erb
<div id="<%= dom_id artifact %>">
  <p>
    <strong>Name:</strong>
    <%= artifact.name %>
  </p>

  <p>
    <strong>Key:</strong>
    <%= artifact.key %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= artifact.project_id %>
  </p>

</div>

app/views/artifacts/_form.html.erb
<%= form_for @artifact, :html => { :class => "form-horizontal artifact" } do |f| %>

  <% if @artifact.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@artifact.errors.count, "error") %> prohibited this artifact from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @artifact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :key, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :key, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :photo, value: "File to upload", class: 'control-label col-lg-2' %>    
    <div class="controls col-lg-10">
      <%= f.file_field :photo, class: 'form-control' %>            
    </div>
  </div>
 
   <%= f.hidden_field :project_id %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                project_path(@artifact.project_id), :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/artifacts/_list.html.erb
<%- model_class = Artifact -%>
<div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% artifacts.each do |artifact| %>
      <tr>
        <td><%= link_to artifact.name, artifact_path(artifact), class: 'main-link' %></td>
        <td>
        <td>
              <button type="button" class="btn btn-danger"><%= link_to "Delete", 
              artifact_path(artifact, :from => "list"),data: {turbo_method: :delete, 
              turbo_confirm: "Are you sure you want to delete?" } %>  
              </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Artifact', new_artifact_path(project_id: @project.id),
            :class => 'btn btn-success' %>
</div>

     

app/views/artifacts/edit.html.erb
<h1>Editing artifact</h1>

<%= render "form", artifact: @artifact %>

<br>

<div>
<%= link_to 'Back', project_path(@artifact.project_id), :class => 'btn btn-primary'  %>
</div>

app/views/artifacts/new.html.erb
<h1>New artifact</h1>

<%= render "form", artifact: @artifact %>

<br>

<div>
  <%= link_to 'Back', project_path(@artifact.project_id), :class => 'btn btn-primary'  %>
</div>

app/views/artifacts/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h3><%= @artifact.name %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @artifact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @artifact.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= Project.find(@artifact.project_id).title %></dd>
</dl>
<%= image_tag(@artifact.photo, width: 200) if @artifact.photo.attached? %>
<br>
<br>
<%= link_to 'Back', project_path(@artifact.project_id), :class => 'btn btn-primary'  %>
<button type="button" class="btn btn-primary"><%= link_to "Edit", 
              edit_artifact_path(@artifact) %>  
              </button>
<button type="button" class="btn btn-danger"><%= link_to "Delete", 
               artifact_path(@artifact),data: {turbo_method: :delete, 
              turbo_confirm: "Are you sure you want to delete?" } %>  
              </button>

app/views/checkouts/show.html.erb
<h1>Checkout!</h1>
<p>Upgrade now to have unlimited projects and unlimited artifacts to store. Manage all of your projects now with project management service.</p>
<ul>
    <strong>Subscribe now for $19.99 a month.</strong>
</ul>
<%= render partial: 'pay/stripe/checkout_button', locals: {
    session: @checkout_session,
    title: "Buy now"
} %>

app/views/checkouts/success.html.erb
<h1>Congrats!</h1>
<p>You just subscripted to the Project Management App.</p>
<% @line_items.each do |item|%>
    <% product = Stripe::Product.retrieve(item.price.product)%>
    <h3><%= item.description %></h3>
<% end %>
<h2>Total amount $<%= @session.amount_total.to_f / 100 %> </h2>
<br>

app/views/home/index.html.erb
<% if current_user %>

<%= render 'projects/list'%>

<% else %>
<div class="jumbotron text-center">
    <h2>Welcome to the Project Management App.</h2>
</div>

<div class="row">
    <div class="col-sm-3 mx-auto">
        <div class="card mx-auto">
            <div class="card-body mx-auto">
            <h5 class="card-title mx-auto">Premium Plan</h5>
            <div class="features mx-auto">
                <ul>
                <li>Unlimited Image Uploads</li>
                <li>Responsive design</li>
                <li>Access anywhere</li>
                </ul>
            </div>
            <p class="card-text">Subscription: $19.99</p>
                <%= link_to 'Checkout', checkout_path, class: 'btn btn-success sign-up' %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <%= link_to "Project Manager", root_path, class: "navbar-brand", id: "logo" %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <% if current_user %>
          <ul class="navbar-nav mr-auto">
            <li><%= link_to('New Project', new_project_path, class: 'nav-link') %></li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %> 
                        Edit profile
                      <% end %>
                  </li>
            </ul>
          </ul>
          <%end%>
          <% if current_user %>
           <ul class="navbar-nav ms-auto">
              <li class="nav-item user-name">
              <%= current_user.email %>
              </li>
            <% if !current_user.paid %>
            <li class="nav-item">
              <%= link_to 'Upgrade Now!', checkout_path, class: 'btn btn-success logout-button'%>
            </li>
            <% else %>
              <p class="mt-2 logout-button"><span class="badge text-bg-success">Subscribed</span></p>
              <% end %>
          <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-secondary logout-button', data: {turbo_method: :delete} %>
            </li>
            </ul>
            <% else %>
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-secondary logout-button', data: {turbo_method: :get} %>
            </li>
            </ul>
            <% end %>
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasProjectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>

  </head>

  <body>
    <%# nav %>
    <%= render 'layouts/navigation' %>
     <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal artifact" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :details, :class => 'form-control' %>
    </div>
  </div>


  <div class='mb-3'>
    <%= f.label :expected_completion_date, style: "display: block" %>
    <%= f.date_field :expected_completion_date %>
  </div>

     <%= f.hidden_field :user_id %>

<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/projects/_list.html.erb
<div class="page-header">
  <h1>Projects</h1>
</div>

<% if current_user.projects.count > 0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Expected Completion Date</th>
    </tr>
  </thead>
  <tbody>
    <% project = Project.all %>
        <% project.each do |project| %>
        <% if project.user_id == current_user.id%>
        <tr>
            <td><%= project.title%></td>
            <td><%= project.details %></td>
            <td><%= project.expected_completion_date %></td>
            <td><%= link_to 'Show project', project, class: 'btn btn-primary'%></td>
        </tr>
        <% end %>
        <%end%>
  </tbody>
</table>
<% else %>
      <p class="lead">You don't have any projects</p>
<% end %>
<%= link_to('New Project', new_project_path, class: 'btn btn-primary') %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= project.details %>
  </p>

  <p>
    <strong>Expected completion date:</strong>
    <%= project.expected_completion_date %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/new.html.erb
<div class='row'>
  <div class = 'col-10'>
      <h1>New project</h1>

      <%= render "form", project: @project %>

      <br>

    </div>
</div>

app/views/projects/show.html.erb
<div class="page-header">
  <h2><Strong><%= @project.title %></Strong></h2>
</div>

<dl class="dl-horizontal">
  <dd><%= @project.details %></dd>

  <h5><strong>Estimated completion date:</strong></h5>
  <% if @project.expected_completion_date != nil %>
  <dd>
    <%= @project.expected_completion_date %>
    </dd>
    <% else %>
    <dd>
      <i> Edit to add a date</i>
    </dd>
    <%end%>

</dl>
<button type="button" class="btn btn-primary"><%= link_to "Edit", 
              edit_project_path(@project) %>  
              </button>
<button type="button" class="btn btn-danger"><%= link_to "Delete", 
              project_path(@project),data: {turbo_method: :delete, 
              turbo_confirm: "Are you sure you want to delete?" } %>  
              </button>
<div class='container mt-5'>
  <div></div>

<h3>Artifacts</h3>
<%= render 'artifacts/list', artifacts: @project.artifacts %>
<br />
<br />
</div>
<%= link_to 'Return to Home', root_path, :class => 'btn btn-secondary'  %>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>
<h1>Users#index</h1>